# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('query', models.CharField(blank=True, max_length=200, verbose_name='query')),
                ('owner', models.CharField(blank=True, choices=[('', 'Anyone'), ('me', 'Me'), ('not me', 'Not me')], max_length=100)),
                ('live', models.NullBooleanField(default=None, verbose_name='live')),
                ('go_live_at', models.CharField(blank=True, choices=[('now-14d', 'Comming 2 weeks'), ('now-7d', 'Comming week'), ('now-3d', 'Comming 3 days'), ('now-2d', 'Comming 2 days'), ('now-1d', 'now - tomorrow midnight'), ('now-mn', 'now - midnight'), ('now-3h', 'Comming 3 hours'), ('now-2h', 'Comming 2 hours'), ('now-1h', 'Comming hour'), ('today', 'Today'), ('1h-now', 'Past hour'), ('2h-now', 'Past 2 hours'), ('3h-now', 'Past 3 hours'), ('mn-now', 'Past midnight - now'), ('2d-now', 'Past 2 days'), ('3d-now', 'Past 3 days'), ('7d-now', 'Past week'), ('14d-now', 'Past 2 weeks')], max_length=100, verbose_name='go live date/time')),
                ('expire_at', models.CharField(blank=True, choices=[('now-14d', 'Comming 2 weeks'), ('now-7d', 'Comming week'), ('now-3d', 'Comming 3 days'), ('now-2d', 'Comming 2 days'), ('now-1d', 'now - tomorrow midnight'), ('now-mn', 'now - midnight'), ('now-3h', 'Comming 3 hours'), ('now-2h', 'Comming 2 hours'), ('now-1h', 'Comming hour'), ('today', 'Today'), ('1h-now', 'Past hour'), ('2h-now', 'Past 2 hours'), ('3h-now', 'Past 3 hours'), ('mn-now', 'Past midnight - now'), ('2d-now', 'Past 2 days'), ('3d-now', 'Past 3 days'), ('7d-now', 'Past week'), ('14d-now', 'Past 2 weeks')], max_length=100, verbose_name='expiry date/time')),
                ('expired', models.NullBooleanField(default=None, verbose_name='expired')),
                ('locked', models.NullBooleanField(default=None, verbose_name='locked')),
                ('has_unpublished_changes', models.NullBooleanField(default=None, verbose_name='has unpublished changes')),
                ('list_length', models.PositiveIntegerField(default=5, verbose_name='list length')),
                ('total_count', models.BooleanField(default=False, verbose_name='display total count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='contenttypes.ContentType', verbose_name='content type')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by user')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'report',
            },
            bases=(wagtail.wagtailsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ReportPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by user')),
                ('for_users', models.ManyToManyField(blank=True, help_text='All users that will have this panel displayed on their dashboard.', related_name='report_panel_for_users', to=settings.AUTH_USER_MODEL)),
                ('reports', models.ManyToManyField(blank=True, help_text='All reports you like to display in this panel.', to='wagtailreports.Report')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'report panel',
            },
            bases=(wagtail.wagtailsearch.index.Indexed, models.Model),
        ),
    ]
